#ifndef GS_DESIGNOPTIONAPI_EXPORT_HPP
#define GS_DESIGNOPTIONAPI_EXPORT_HPP

#include "PlatformDLLExport.hpp"

#if defined (DESIGNOPTIONAPI_COMPILE)
	#define DESIGNOPTIONAPI_EXPORT		PLATFORM_DLL_EXPORT
#else
	#define DESIGNOPTIONAPI_EXPORT		PLATFORM_DLL_IMPORT
#endif


#endif
