#ifndef ARCHICADAPI_EXPORT_HPP
#define ARCHICADAPI_EXPORT_HPP

// from GSRoot
#include "PlatformDLLExport.hpp"


#ifdef ARCHICADAPI_COMPILE
	#define ARCHICADAPI_EXPORT PLATFORM_DLL_EXPORT
	#define ARCHICADAPI_EXPORT_FORTEST PLATFORM_DLL_EXPORT
#else
	#define ARCHICADAPI_EXPORT PLATFORM_DLL_IMPORT
	#define ARCHICADAPI_EXPORT_FORTEST PLATFORM_DLL_IMPORT
#endif


#endif /* ARCHICADAPI_EXPORT_HPP */
