#ifndef CADVISUALIZATION_EXPORT
#define CADVISUALIZATION_EXPORT

#pragma once

#include "PlatformDLLExport.hpp"

#if defined (CADINFRASTRUCTURE_DLL_COMPILE)
	#define CADINFRASTRUCTURE_DLL_EXPORT		PLATFORM_DLL_EXPORT
#else
	#define CADINFRASTRUCTURE_DLL_EXPORT		PLATFORM_DLL_IMPORT
#endif

#endif
