#!/bin/bash
# HBIM Plugin CEF Cache Clearing Helper
# 提供清除Archicad中CEF浏览器缓存的指导

set -e

echo "=============================================="
echo "HBIM Plugin - CEF Cache Clearing Helper"
echo "=============================================="
echo ""
echo "当插件版本更新后，如果Archicad中显示的版本不正确，"
echo "可能是CEF (Chromium Embedded Framework) 浏览器缓存导致的。"
echo ""
echo "请按照以下步骤清除缓存："
echo ""

echo "1. 在Archicad中打开插件面板："
echo "   - 菜单: 测试 → NewPlugin"
echo ""
echo "2. 打开开发者工具："
echo "   - 按 F12 键"
echo "   - 或 右键点击插件面板空白处 → 检查"
echo ""
echo "3. 切换到 Application (应用程序) 标签页："
echo "   - 如果看不到Application标签，点击 >> 查看更多标签"
echo ""
echo "4. 清除存储数据："
echo "   - 在左侧面板选择 Storage → Clear storage"
echo "   - 在右侧点击 Clear site data 按钮"
echo ""
echo "5. 关闭开发者工具："
echo "   - 按 F12 键 或 点击关闭按钮"
echo ""
echo "6. 强制重新加载插件面板："
echo "   - 按 Ctrl+Shift+R (Windows) 或 Cmd+Shift+R (macOS)"
echo "   - 或 关闭插件面板后重新打开"
echo ""
echo "7. 验证版本："
echo "   - 插件面板右上角应显示版本: V0.2.13.71"
echo ""

echo "如果问题仍然存在，请尝试："
echo ""
echo "a) 重启Archicad："
echo "   - 完全退出Archicad"
echo "   - 重新启动Archicad"
echo "   - 再次打开插件面板"
echo ""
echo "b) 手动删除CEF缓存文件 (macOS)："
echo "   - 关闭Archicad"
echo "   - 删除缓存目录:"
echo "     ~/Library/Caches/GRAPHISOFT/ARCHICAD 29/CEF"
echo "   - 重新启动Archicad"
echo ""
echo "c) 验证插件安装版本："
echo "   - 运行以下命令检查安装的插件版本："
echo "     grep -A1 CFBundleVersion ~/Library/Application\\\\ Support/GRAPHISOFT/ARCHICAD\\\\ 29/Add-Ons/MergedPlugin.bundle/Contents/Info.plist"
echo ""

echo "=============================================="
echo "更多详细信息请参考:"
echo "- TESTING.md 中的故障排除部分"
echo "- 或运行 ./validate_plugin.sh 检查插件状态"
echo "=============================================="