#ifndef GS_ANALYTICALMODELAPI_EXPORT
#define GS_ANALYTICALMODELAPI_EXPORT

// from GSRoot
#include "PlatformDLLExport.hpp"


#if defined (ANALYTICALMODELAPI_COMPILE)
	#define ANALYTICALMODELAPI_EXPORT		PLATFORM_DLL_EXPORT
#else
	#define ANALYTICALMODELAPI_EXPORT		PLATFORM_DLL_IMPORT
#endif


#endif /* GS_ANALYTICALMODELAPI_EXPORT */
