#ifndef GS_ACAPI_ZONEBOUNDARYQUERYAPIEXPORT_HPP
#define GS_ACAPI_ZONEBOUNDARYQUERYAPIEXPORT_HPP

// from GSRoot
#include "PlatformDLLExport.hpp"


#ifdef ZONEBOUNDARYQUERYAPI_COMPILE
	#define ZONEBOUNDARYQUERYAPI_EXPORT PLATFORM_DLL_EXPORT
#else
	#define ZONEBOUNDARYQUERYAPI_EXPORT PLATFORM_DLL_IMPORT
#endif


#endif /* GS_ACAPI_ZONEBOUNDARYQUERYAPIEXPORT_HPP */
