#ifndef GS_ACAPI_PROPERTYOPERATIONSAPIEXPORT_HPP
#define GS_ACAPI_PROPERTYOPERATIONSAPIEXPORT_HPP

// from GSRoot
#include "PlatformDLLExport.hpp"


#ifdef PROPERTYOPERATIONSAPI_COMPILE
	#define PROPERTYOPERATIONSAPI_EXPORT PLATFORM_DLL_EXPORT
#else
	#define PROPERTYOPERATIONSAPI_EXPORT PLATFORM_DLL_IMPORT
#endif


#endif /* GS_ACAPI_PROPERTYOPERATIONSAPIEXPORT_HPP */
