#ifndef PROTECTIONTEST_RESIDS_HPP
#define PROTECTIONTEST_RESIDS_HPP

#define PROTECTIONTEST_ABOUT_STRINGSID			   32000
#define PROTECTIONTEST_MENU_STRINGSID			   32500
#define PROTECTIONTEST_PROMPT_STRINGSID			   32520

#define PROTECTIONTEST_ALERT_COMMAND_OK_RESID	   32590
#define PROTECTIONTEST_ALERT_COMMAND_ERROR_RESID   32591
#define PROTECTIONTEST_ALERT_PROTECTION_INFO_RESID 32592

#endif // PROTECTIONTEST_RESIDS_HPP