#ifndef TW_CONTROL_RESOURCE_IDS_HPP
#define TW_CONTROL_RESOURCE_IDS_HPP

#define MDID_RES_ID							32500

#define ADD_ON_STRINGS_RES_ID				32000

#define TEAMWORK_CONTROL_MENU_STRINGS_RES_ID		32500
#define TEAMWORK_CONTROL_STATUS_BAR_STRINGS_RES_ID	32600

#define EMBEDDED_LIBRARY_MENU_STRINGS_RES_ID		32501
#define EMBEDDED_LIBRARY_STATUS_BAR_STRINGS_RES_ID	32601

#endif
