#if !defined (RESOURCES_HPP)
#define RESOURCES_HPP

#define	IFC_TEST_ADDON_NAME							32000

#define	IFCAPI_TEST_MENU_STRINGS				    32501
#define	IFCAPI_TEST_MENU_PROMPT_STRINGS		        32601

#define	IFCPRESETCOMMANDS_TEST_RESID_LOCSTRINGS		32300

#endif
